# Generated by Django 4.0.6 on 2022-08-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goPoll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
